### ISSUE TITLE
Add support for IPv4 TTL `increment` and `decrement` patterns

### ISSUE THREAD

**Issue by bortok** [open-traffic-generator/ixia-c#93]
The following OTG config fails on 

- ixiacom/ixia-c-controller:0.0.1-3027
- ixiacom/ixia-c-traffic-engine:1.4.1.29

```
  - choice: ipv4
    ipv4:
      time_to_live:
        choice: increment
        increment:
          start: 1
          step: 1
          count: 2
```
with an error message

```
"Error occurred while setting Traffic config for user common:Error setting frame for flow p1>p2:Could not add IPv4:Failed constructing IPv4 header:unsupported pattern for IPv4 TTL: increment"
```
