### ISSUE TITLE
`store_forward` latency mode is not supported

### ISSUE THREAD

**Issue by bortok** [open-traffic-generator/ixia-c#99]
Ixia-c does not accept `store_forward` latency mode, while `cut_through` works fine:

```
flows:
- duration:
    choice: fixed_packets
    fixed_packets:
      gap: 12
      packets: 1000
  metrics:
    enable: true
    latency:
      enable: true
      mode: store_forward
    loss: false
    timestamps: false
  name: f1
```

```
{
  "errors": [
    "Latency mode \"store forward\" is currently not supported for flow \"f1\""
  ]
}
```

as opposed to

```
flows:
- duration:
    choice: fixed_packets
    fixed_packets:
      gap: 12
      packets: 1000
  metrics:
    enable: true
    latency:
      enable: true
      mode: cut_through
    loss: false
    timestamps: false
  name: f1
```

```
{"choice":"flow_metrics", "flow_metrics":[{"name":"f1", "transmit":"started", "frames_tx":"3", "frames_rx":"3", "bytes_tx":"0", "bytes_rx":"246", "frames_tx_rate":0, "frames_rx_rate":0, "latency":{"minimum_ns":67580, "maximum_ns":957940, "average_ns":432933}}]}
{"choice":"flow_metrics", "flow_metrics":[{"name":"f1", "transmit":"started", "frames_tx":"360", "frames_rx":"360", "bytes_tx":"0", "bytes_rx":"29520", "frames_tx_rate":703, "frames_rx_rate":703, "latency":{"minimum_ns":8700, "maximum_ns":24144420, "average_ns":3400081}}]}
{"choice":"flow_metrics", "flow_metrics":[{"name":"f1", "transmit":"started", "frames_tx":"719", "frames_rx":"718", "bytes_tx":"0", "bytes_rx":"58876", "frames_tx_rate":705, "frames_rx_rate":704, "latency":{"minimum_ns":8700, "maximum_ns":24162360, "average_ns":3139900}}]}
{"choice":"flow_metrics", "flow_metrics":[{"name":"f1", "transmit":"stopped", "frames_tx":"1000", "frames_rx":"1000", "bytes_tx":"0", "bytes_rx":"82000", "frames_tx_rate":700, "frames_rx_rate":673, "latency":{"minimum_ns":8700, "maximum_ns":24162360, "average_ns":3205957}}]}
```

Tested on
```
image: ghcr.io/open-traffic-generator/ixia-c-controller:0.0.1-3182
image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.6.0.9
```
